### ISSUE TITLE
Bad parsing if I remove 2nd paragraph in last definition

### ISSUE THREAD

**Issue by johncja** [markdown-it/markdown-it-deflist#4]
Here is example to try:

([Or permalink](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Term%201%5Cn%5Cn%3A%20Definition%20of%20term%201%5Cn%5Cn%20%20Definition%20continuation...%5Cn%5CnTerm%202%5Cn%5Cn%3A%20Definition%20of%20term%202%5Cn%5Cn%20%20Definition%20continuation...%5Cn%5CnTerm%203%5Cn%5Cn%3A%20Definition%20of%20term%203%5Cn%5Cn%20%20Definition%20continuation...%20Could%20not%20be%20removed%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D))

``` md
Term 1

: Definition of term 1

  Definition continuation...

Term 2

: Definition of term 2

  Definition continuation...

Term 3

: Definition of term 3

  Definition continuation... Could not be removed
```

It works well. But, if I try to remove the last continuation, the parsing will be wrong.

It doesn't affect the demo. The demo works perfectly: [permalink, there are no errors](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22Term%201%5Cn%5Cn%3A%20Definition%20of%20term%201%5Cn%5Cn%20%20Definition%20continuation...%5Cn%5CnTerm%202%5Cn%5Cn%3A%20Definition%20of%20term%202%5Cn%5Cn%20%20Definition%20continuation...%5Cn%5CnTerm%203%5Cn%5Cn%3A%20Definition%20of%20term%203%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

But in my local testing, for some reason, it fails.

Instead of properly rendering, the `<p>` tags are missings. That's what I mean:

``` html
<dl>
<dt>Term 1</dt>
<dd>Definition of term 1Definition continuation...</dd>
<dt>Term 2</dt>
<dd>Definition of term 2Definition continuation...</dd>
<dt>Term 3</dt>
<dd>Definition of term 3</dd>
</dl>
```

And as a result, the text is just broken. Like this:

```
Definition of term 1Definition continuation...
```

Vitaly, is it expected behaviour by default? I see, in demo it works perfectly, without any errors, but probably you used some special code in `index.js` to fix this issue (and this issue is well known to you)? Thanks.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.js#L135 demo has no special code, it just activates plugin.

Try to create separate repo with minimal example how to reproduce your problem (example should be as minimal as possible, for node.js). 2 samples - good and bad

**Comment by johncja** [comment]
I use browser version and not familiar with Node. But, it seems, there is a little mistype in current dist version of plugin.

A simple diff between `index.js` and `markdown-it-deflist.js` shows, that `tight = true;` is located in different places.

markdown-it-deflist.js (buggy):

    OUTER:
    for (;;) {
      tight = true;
      prevEmptyEnd = false;

index.js (correct result):

    // Start list
    listTokIdx = state.tokens.length;
    tight = true;

Are you changed it intentionally, or it is really just a mistype (bug)?

**Comment by puzrin** [comment]
Seems i forgot to rebuild browser files in prev release. 2.0.2 should fix this.
